# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  action:
    required: false
    default: "complete"
  pr:
    required: false
  organization_id:
    required: false
  location:
    required: true
runs:
  using: 'docker'
  image: '../Dockerfile'
  entrypoint: '/notify.sh'
  args:
    - ${{ inputs.pr }}