# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  action:
    required: false
    default: "complete"
  pr:
    required: false
  registry:
    required: false
  location_file:
    required: false
  image_tag:
    required: false
  location_name:
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  post-entrypoint: 'clean_entrypoint.sh'
  args:
    - ${{ inputs.pr }}