# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  action:
    required: false
    default: "complete"
  pr:
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pr }}