# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  pr:
    required: false
  image_tag:
    required: false
  organization_id:
    required: false
  location:
    required: true
runs:
  using: 'docker'
  image: '764506304434.dkr.ecr.us-west-2.amazonaws.com/dagster-cloud-cli-dev:the_action'
  # image: '../Dockerfile'
  entrypoint: '/deploy.sh'
  args:
    - ${{ inputs.pr }}
