on: [pull_request]

jobs:
  dagster_cloud_build_push:
    runs-on: ubuntu-latest
    name: Dagster Cloud
    strategy:
      matrix:
        # Here, define the code locations that should be built and deployed
        location:
          - name: test
            build_folder: example
            registry: 764506304434.dkr.ecr.us-west-2.amazonaws.com/branch-deployments-gh-action-test
            location_file: example/workspace.yaml
          - name: test2
            build_folder: example
            registry: 764506304434.dkr.ecr.us-west-2.amazonaws.com/branch-deployments-gh-action-test
            location_file: example/workspace.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.location.build_folder }}
          push: true
          tags: "${{ matrix.location.registry }}:${{ github.sha }}"
          labels: |
            branch=${{ github.head_ref }}

      - name: Dagster Cloud deploy
        uses: ./ # Uses an action in the root directory
        with:
          action: complete
          pr: "${{ github.event.number }}"
          registry: ${{ matrix.location.registry }}
          location_file: ${{ matrix.location.location_file }}
          image_tag: ${{ github.sha }}
          location_name: ${{ matrix.location.name }}
          dagster_cloud_url: https://pied-piper.dogfood.dagster.cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}